name: DevandTesting
main: com.tylerhyperhd.devandtesting.DevandTesting
version: 1.3.1-ALPHA
author: tylerhyperHD
description: Made to test a server and its capabilities.
commands:
  creative:
    description: Sets your gamemode to creative.
    usage: /<command> [player]
    aliases: [gmc, ecreative]
  survival:
    description: Sets your gamemode to survival.
    usage: /<command> [player]
    aliases: [gms, esurvival]
  admin:
    description: Go into and out of admin mode.
    usage: /<command>
  website:
    description: Shows our website for ya.
    usage: /<command>
  gamemode:
    description: Change your gamemode.
    usage: /<command> [mode] [player]
    aliases: [gm, egamemode]
  color:
    description: Change ur chat color.
    usage: /<command> [color | num | off]
  kill:
    description: Kills a player.
    usage: /<command> [player]
    aliases: [ekill]
  lagg:
    description: Lagg manager on steroids.
    usage: /<command> [clear]
    aliases: [rd]
  multirun:
    description: Run a command a set amount of times.
    usage: /<command> [times] [cmd]
  dab:
    description: Dab.
    usage: /<command>
  spectator:
    description: Go in spectator mode.
    usage: /<command>
  pkillswitch:
    description: Disables all plugins except DevandTesting OR disables all plugins.
    usage: /<command> [everything]
  clearchat:
    description: Clears the entire chat.
    usage: /<command>
    aliases: [cc]
  purple:
    description: Insane only command. Graces the world with purple.
    usage: /<command>
permissions:
    devandtesting.admin:
        description: Allows you to change to admin mode.
        default: op
    devandtesting.admin.others:
        description: Allows you to change other players admin mode. Permission must be invoked to use it.
        default: false
    devandtesting.color:
        description: Allows you to change your chat color.
        default: op
    devandtesting.insane:
        description: Allows use of the insane command. Disabled unless given perms.
        default: false